name: Verify PRs

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "Your PR is ${PR}"
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      env:
        SONAR_LOGIN: ${{ secrets.sonar_login }}
        PR: ${{ github.event.number }}
      run: |
           printenv
           mvn verify sonar:sonar \
           -Dsonar.projectKey=softwaretalks_jangul \
           -Dsonar.organization=softwaretalks \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.pullrequest.key=$PR
           -Dsonar.pullrequest.branch=master
           -Dsonar.login=$SONAR_LOGIN

